#!/usr/bin/env bash

HELP=0
while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    --help|-h)
    HELP=1
    ;;
    *)
    EMAILS=$1
    ;;
esac
shift # past argument or value
done

echoerr() { echo "$@" 1>&2; }

if [[ $HELP -eq 1 ]]; then
    echo "Usage: speedtestmail <comma separated email addresses>"
    echo ""
    echo ""
    echo "examples:"
    echo "        $ speedtestmail someone@gmail.com"
    echo "        $ speedtestmail someone@gmail.com,someoneelse@gmail.com"
    exit 0
fi

if [ ! -e /usr/local/bin/speedtest-cli ]; then
    echoerr "Please install speedtest-cli from https://github.com/sivel/speedtest-cli"
    exit 1
fi

echo "Getting speedtest metrics..."
data=$("/usr/local/bin/speedtest-cli")

hostname=$(hostname)
echo "Hostname: $hostname"

updown=$(echo "$data" | awk '/Upload|Download/' | paste -s -d ", " -  )
echo "Speed: $updown"

ipline=$(echo "$data" | grep "Testing from")
ipline=${ipline##* } #Extract IP from IP Line
ip=${ipline%%...} 
echo "External IP: $ip"

subject="$hostname$ip>>> $updown"

for EMAIL in $(echo $EMAILS | sed "s/,/ /g")
do
    echo "Sending mail with $subject to $EMAIL"
    echo "$data" | mail -s "$subject" $EMAIL
done
exit 0
